# Generated by Django 4.0.4 on 2022-04-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='body',
            field=models.TextField(),
        ),
    ]
